CREATE TABLE [dbo].[User]
(
	[UserID] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[UserName] NVARCHAR(50) NOT NULL,
	[PasswordHash] NVARCHAR(255) NOT NULL,
	[UserDOB] DATE NULL,
	[BodyWeight] DECIMAL(5,1) NULL,
	[Height] DECIMAL(5,1) NULL,

	CONSTRAINT [UQ_User_UserName] UNIQUE (UserName)
)
