CREATE TABLE [dbo].[WeightGoal]
(
	[WGoalId] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[GoalID] INT NOT NULL,
	[TargetBW] DECIMAL(5,1) NOT NULL,
	[StartBW] DECIMAL(5,1) NOT NULL,

	CONSTRAINT [FK_WeightGoal_Goal_GoalID] FOREIGN KEY (GoalID) REFERENCES [dbo].[UserGoal](GoalID)
)
